# Nigerian foodstuff catalog - curated seed data
# Images from Unsplash (free-to-use)

_IMG = {
    "egusi": "https://images.unsplash.com/photo-1601001435957-74f0958a93c6?auto=format&fit=crop&w=800&q=80",
    "ogbono": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    "oha": "https://images.unsplash.com/photo-1583258292688-d0213dc5a3a8?auto=format&fit=crop&w=800&q=80",
    "bitterleaf": "https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80",
    "uziza": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    "stockfish": "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=800&q=80",
    "dryfish": "https://images.unsplash.com/photo-1565280654386-36ccd3d6e79a?auto=format&fit=crop&w=800&q=80",
    "crayfish": "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80",
    "smoked_turkey": "https://images.unsplash.com/photo-1606728035253-49e8a23146de?auto=format&fit=crop&w=800&q=80",
    "goat_meat": "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=800&q=80",
    "garri_yellow": "https://images.unsplash.com/photo-1610663711502-35f870cfaea2?auto=format&fit=crop&w=800&q=80",
    "garri_white": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    "fufu": "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=800&q=80",
    "semo": "https://images.unsplash.com/photo-1586444248902-2f64eddc13df?auto=format&fit=crop&w=800&q=80",
    "pounded_yam": "https://images.unsplash.com/photo-1604908554007-1c5a7b7c54da?auto=format&fit=crop&w=800&q=80",
    "rice": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    "beans": "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=800&q=80",
    "plantain": "https://images.unsplash.com/photo-1552709607-08d00227833d?auto=format&fit=crop&w=800&q=80",
    "plantain_chips": "https://images.unsplash.com/photo-1599490659213-e2b9527bd087?auto=format&fit=crop&w=800&q=80",
    "yam": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    "palm_oil": "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=800&q=80",
    "groundnut_oil": "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=800&q=80",
    "maggi": "https://images.unsplash.com/photo-1605478573458-eab2e5a4bdf4?auto=format&fit=crop&w=800&q=80",
    "uda": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80",
    "ehuru": "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=800&q=80",
    "pepper": "https://images.unsplash.com/photo-1583456999208-5d8ab95dbd4d?auto=format&fit=crop&w=800&q=80",
    "ginger": "https://images.unsplash.com/photo-1603048297172-c92544798d5a?auto=format&fit=crop&w=800&q=80",
    "chin_chin": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
    "puff_puff": "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?auto=format&fit=crop&w=800&q=80",
    "meat_pie": "https://images.unsplash.com/photo-1568051243851-f9b136146e97?auto=format&fit=crop&w=800&q=80",
    "malta_guinness": "https://images.unsplash.com/photo-1608274812376-b3079f6a6c82?auto=format&fit=crop&w=800&q=80",
    "zobo": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
    "kunu": "https://images.unsplash.com/photo-1624806992066-5b46eec2bc4d?auto=format&fit=crop&w=800&q=80",
    "dudu_osun": "https://images.unsplash.com/photo-1600857062241-98e5dba7f214?auto=format&fit=crop&w=800&q=80",
    "shea_butter": "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80",
    "chewing_stick": "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?auto=format&fit=crop&w=800&q=80",
    "adire": "https://images.unsplash.com/photo-1604908554007-1c5a7b7c54da?auto=format&fit=crop&w=800&q=80",
    "kolanut": "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80",
    "bitter_kola": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
    "tiger_nuts": "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80",
    "dried_hibiscus": "https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=800&q=80",
    "suya_spice": "https://images.unsplash.com/photo-1599909366516-6c1d4c1f8a35?auto=format&fit=crop&w=800&q=80",
    "ofada_rice": "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=800&q=80",
    "honey_beans": "https://images.unsplash.com/photo-1515543904379-3d757afe72e4?auto=format&fit=crop&w=800&q=80",
    "locust_beans": "https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=800&q=80",
}


def _p(name, slug, category, subcategory, price, desc, image_key, weight, tags, featured=False, stock=100, origin="Nigeria"):
    return {
        "name": name, "slug": slug, "category": category, "subcategory": subcategory,
        "price": price, "description": desc, "image": _IMG[image_key], "weight": weight,
        "tags": tags, "featured": featured, "stock": stock, "origin": origin,
        "rating": 4.8, "reviews_count": 0,
    }


PRODUCTS_SEED = [
    # Soup Ingredients
    _p("Premium Egusi (Melon Seeds)", "egusi-seeds", "Soup Ingredients", "Seeds", 12.99,
       "Finely ground premium egusi seeds — the heart of Nigeria's most iconic soup. Creamy, nutty, and full of tradition.",
       "egusi", "500g", ["egusi", "soup", "seeds"], featured=True),
    _p("Ogbono (Wild Mango Seeds)", "ogbono", "Soup Ingredients", "Seeds", 14.99,
       "Ground ogbono for silky, drawing ogbono soup. Rich, earthy flavor straight from Eastern Nigeria.",
       "ogbono", "250g", ["ogbono", "soup", "draw"], featured=True),
    _p("Oha Leaves (Dried)", "oha-leaves", "Soup Ingredients", "Leaves", 9.99,
       "Fragrant dried oha leaves — essential for authentic Oha soup and Nsala. Sun-dried to lock in aroma.",
       "oha", "100g", ["oha", "leaves", "igbo"], featured=True),
    _p("Bitterleaf (Onugbu)", "bitterleaf", "Soup Ingredients", "Leaves", 8.49,
       "Washed and dried bitterleaf for authentic Ofe Onugbu. Balanced bitterness, clean prep.",
       "bitterleaf", "150g", ["bitterleaf", "onugbu"]),
    _p("Uziza Leaves", "uziza-leaves", "Soup Ingredients", "Leaves", 7.99,
       "Aromatic uziza leaves with a signature peppery kick. Perfect for pepper soup and Nsala.",
       "uziza", "50g", ["uziza", "leaves", "aromatic"]),
    _p("Utazi Leaves", "utazi-leaves", "Soup Ingredients", "Leaves", 7.49,
       "Slightly bitter utazi leaves for soups and Isi Ewu. Delivers that authentic Igbo flavor.",
       "oha", "50g", ["utazi", "leaves"]),
    _p("Locust Beans (Iru/Ogiri)", "locust-beans", "Soup Ingredients", "Seasoning", 6.99,
       "Fermented locust beans — the soul of Yoruba soups. Iru adds smoky umami depth.",
       "locust_beans", "200g", ["iru", "ogiri", "fermented"]),

    # Proteins
    _p("Premium Stockfish (Okporoko)", "stockfish", "Proteins", "Dried Fish", 24.99,
       "Norwegian-sourced stockfish — the king of Nigerian soups. Pre-softened, ready to slice.",
       "stockfish", "400g", ["stockfish", "okporoko"], featured=True),
    _p("Smoked Catfish (Mangala)", "smoked-catfish", "Proteins", "Dried Fish", 18.99,
       "Slow-smoked catfish with smoky aroma. Perfect for pepper soup and fisherman's soup.",
       "dryfish", "300g", ["catfish", "smoked"]),
    _p("Ground Crayfish", "crayfish", "Proteins", "Seafood", 10.99,
       "Fine-milled crayfish powder. Adds deep umami to every pot. Freshly packed.",
       "crayfish", "250g", ["crayfish", "umami"], featured=True),
    _p("Smoked Turkey Wings", "smoked-turkey", "Proteins", "Frozen", 22.99,
       "Plump smoked turkey wings for jollof, stews and peppered turkey. Delivered frozen.",
       "smoked_turkey", "1kg", ["turkey", "smoked", "frozen"]),
    _p("Goat Meat (Assorted)", "goat-meat", "Proteins", "Frozen", 28.99,
       "Assorted goat meat, butcher-cut for pepper soup, Nkwobi, and Asun.",
       "goat_meat", "1kg", ["goat", "meat", "frozen"]),

    # Grains & Flours
    _p("Yellow Garri (Ijebu)", "yellow-garri", "Grains & Flours", "Garri", 9.99,
       "Fine Ijebu yellow garri — crunchy, tangy, perfect for eba or soaking with groundnuts.",
       "garri_yellow", "2kg", ["garri", "ijebu"], featured=True),
    _p("White Garri (Lebu)", "white-garri", "Grains & Flours", "Garri", 9.49,
       "Classic white garri, mild and versatile. A diaspora staple.",
       "garri_white", "2kg", ["garri", "white"]),
    _p("Fufu Flour", "fufu-flour", "Grains & Flours", "Swallow", 11.99,
       "Ready-to-mix fufu flour. Smooth, stretchy, and deeply satisfying.",
       "fufu", "1kg", ["fufu", "swallow"]),
    _p("Semolina (Semo)", "semolina", "Grains & Flours", "Swallow", 7.99,
       "Smooth semolina for a light swallow that pairs with every soup.",
       "semo", "1kg", ["semo", "swallow"]),
    _p("Pounded Yam Flour", "pounded-yam-flour", "Grains & Flours", "Swallow", 12.99,
       "Authentic pounded yam flour — the taste of Sunday afternoons.",
       "pounded_yam", "1kg", ["iyan", "yam"], featured=True),
    _p("Ofada Rice (Local Brown)", "ofada-rice", "Grains & Flours", "Rice", 14.99,
       "Aromatic local Ofada rice. Perfect with ayamase stew.",
       "ofada_rice", "2kg", ["ofada", "rice", "local"]),
    _p("Honey Beans (Oloyin)", "honey-beans", "Grains & Flours", "Beans", 8.99,
       "Sweet Oloyin beans — the go-to for moi moi and akara.",
       "honey_beans", "1kg", ["beans", "oloyin", "moi-moi"]),
    _p("Black-eyed Beans", "black-eyed-beans", "Grains & Flours", "Beans", 7.99,
       "Clean black-eyed beans, perfect for akara and ewa agoyin.",
       "beans", "1kg", ["beans", "akara"]),

    # Fresh Produce
    _p("Fresh Plantains (Green)", "green-plantains", "Fresh Produce", "Produce", 6.99,
       "Firm green plantains for boli, dodo, or plantain porridge. 5 fingers per pack.",
       "plantain", "pack of 5", ["plantain", "fresh"], featured=True),
    _p("Ripe Plantains", "ripe-plantains", "Fresh Produce", "Produce", 7.49,
       "Sweet, golden ripe plantains — dodo dreams, delivered.",
       "plantain", "pack of 5", ["plantain", "ripe"]),
    _p("Fresh Puna Yam Tuber", "puna-yam", "Fresh Produce", "Produce", 19.99,
       "Premium Puna yam, hand-selected. Ideal for pounded yam, porridge, and asaro.",
       "yam", "1 large tuber", ["yam", "puna"]),
    _p("Scotch Bonnet Peppers (Ata Rodo)", "atarodo", "Fresh Produce", "Peppers", 5.99,
       "Fiery scotch bonnets — Nigeria's signature heat. Delivered fresh.",
       "pepper", "250g", ["pepper", "atarodo"]),
    _p("Fresh Ginger Root", "ginger", "Fresh Produce", "Roots", 4.99,
       "Aromatic ginger root for zobo, pepper soup, and smoothies.",
       "ginger", "500g", ["ginger", "root"]),

    # Oils & Staples
    _p("Red Palm Oil (Zomi)", "palm-oil", "Oils & Staples", "Oils", 13.99,
       "Unrefined red palm oil — deep color, rich flavor. The base of authentic Banga and Ofada stew.",
       "palm_oil", "1L", ["palm oil", "zomi"], featured=True),
    _p("Groundnut Oil", "groundnut-oil", "Oils & Staples", "Oils", 15.99,
       "Pure Nigerian groundnut oil for frying akara, puff-puff, and jollof.",
       "groundnut_oil", "1L", ["oil", "groundnut"]),

    # Spices & Seasoning
    _p("Maggi Cubes (Pack of 50)", "maggi", "Spices & Seasoning", "Cubes", 8.99,
       "The seasoning cube that raised a nation. Pack of 50.",
       "maggi", "50 cubes", ["maggi", "seasoning"]),
    _p("Suya Spice (Yaji)", "suya-spice", "Spices & Seasoning", "Spice Blend", 9.99,
       "Authentic Yaji suya spice — peanut, ginger, chili, and secrets from Kano.",
       "suya_spice", "200g", ["suya", "yaji", "spice"], featured=True),
    _p("Uda (Negro Pepper)", "uda", "Spices & Seasoning", "Whole Spice", 6.99,
       "Fragrant Uda pods for pepper soup and postpartum teas.",
       "uda", "50g", ["uda", "pepper"]),
    _p("Ehuru (Calabash Nutmeg)", "ehuru", "Spices & Seasoning", "Whole Spice", 7.49,
       "Roasted ehuru seeds — warm, nutty, essential for Ofe Nsala.",
       "ehuru", "50g", ["ehuru", "nutmeg"]),

    # Snacks
    _p("Chin Chin (Family Pack)", "chin-chin", "Snacks", "Crunchy", 8.99,
       "Crunchy, buttery chin chin in a family-size pack. Impossible to stop at one.",
       "chin_chin", "500g", ["chinchin", "snack"], featured=True),
    _p("Plantain Chips", "plantain-chips", "Snacks", "Crisps", 5.99,
       "Crispy, lightly salted plantain chips. The Naija airport snack, reimagined.",
       "plantain_chips", "250g", ["plantain", "chips"]),
    _p("Meat Pie Pastry", "meat-pie", "Snacks", "Savory", 12.99,
       "6 buttery, filling-packed meat pies. Delivered frozen, oven-ready.",
       "meat_pie", "pack of 6", ["meatpie", "pastry"]),
    _p("Puff Puff Mix", "puff-puff", "Snacks", "Mix", 6.99,
       "Just-add-water puff puff mix. Golden, fluffy, dangerous.",
       "puff_puff", "500g", ["puffpuff", "mix"]),
    _p("Tiger Nuts (Ofio)", "tiger-nuts", "Snacks", "Nuts", 8.49,
       "Chewy, sweet tiger nuts — and the base of Kunun Aya.",
       "tiger_nuts", "400g", ["tigernuts", "ofio"]),

    # Beverages
    _p("Malta Guinness (Pack of 6)", "malta-guinness", "Beverages", "Non-alcoholic", 14.99,
       "The malt drink of champions. Rich, caramel, non-alcoholic.",
       "malta_guinness", "6x330ml", ["malta", "drink"]),
    _p("Dried Hibiscus (Zobo)", "zobo-leaves", "Beverages", "Herbal", 7.99,
       "Ruby-red hibiscus petals for that iconic chilled Zobo drink.",
       "zobo", "200g", ["zobo", "hibiscus"]),
    _p("Kunu Aya Mix", "kunu-mix", "Beverages", "Herbal", 9.99,
       "Tiger nut kunu mix with dates and ginger. Creamy and refreshing.",
       "kunu", "500g", ["kunu", "drink"]),

    # Beauty & Personal Care
    _p("Dudu Osun African Black Soap (Pack of 3)", "dudu-osun", "Beauty & Personal Care", "Soap", 11.99,
       "Traditional Nigerian black soap — shea butter, honey, cocoa pod ash. 3 bars.",
       "dudu_osun", "3 bars", ["soap", "black soap"], featured=True),
    _p("Raw Shea Butter", "shea-butter", "Beauty & Personal Care", "Skincare", 16.99,
       "100% unrefined Nigerian shea butter. Creamy, nutty, deeply moisturizing.",
       "shea_butter", "250g", ["shea", "skincare"]),
    _p("African Chewing Stick (Orin Ata)", "chewing-stick", "Beauty & Personal Care", "Oral", 5.49,
       "Natural chewing sticks for the traditional fresh-breath ritual.",
       "chewing_stick", "pack of 10", ["chewing stick", "oral"]),

    # Cultural / Special
    _p("Kolanut (Oji)", "kolanut", "Cultural", "Traditional", 14.99,
       "Premium Igbo-style kolanut — for ceremonies, blessings, and offerings.",
       "kolanut", "10 pieces", ["kolanut", "oji"]),
    _p("Bitter Kola (Orogbo)", "bitter-kola", "Cultural", "Traditional", 9.99,
       "Fresh bitter kola seeds — energizing, medicinal, deeply traditional.",
       "bitter_kola", "10 pieces", ["orogbo", "bitterkola"]),
    _p("Ankara Fabric (6 Yards)", "ankara-fabric", "Cultural", "Fabric", 34.99,
       "Hand-selected 6-yard Ankara fabric. Vibrant prints, 100% cotton.",
       "adire", "6 yards", ["ankara", "fabric"]),
]


SUBSCRIPTION_TIERS = [
    {
        "id": "starter",
        "name": "Starter Box",
        "price": 49.99,
        "tagline": "A taste of home for one",
        "description": "Perfect for solo diasporans. 8 essentials curated monthly.",
        "items_count": 8,
        "serves": "1-2 people",
        "benefits": [
            "8 curated essentials (rotated monthly)",
            "Free shipping worldwide",
            "Exclusive recipe cards",
            "Pause or cancel anytime",
        ],
        "image": "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80",
        "color": "primary",
    },
    {
        "id": "family",
        "name": "Family Box",
        "price": 89.99,
        "tagline": "Sunday rice for the whole family",
        "description": "14 hand-picked essentials for the whole family. Best value.",
        "items_count": 14,
        "serves": "3-5 people",
        "benefits": [
            "14 curated essentials (rotated monthly)",
            "Free priority shipping",
            "Exclusive recipe cards + cooking video",
            "10% off all add-ons",
            "Pause or cancel anytime",
        ],
        "image": "https://images.unsplash.com/photo-1607877361964-d5c3c7aa4f9a?auto=format&fit=crop&w=800&q=80",
        "color": "secondary",
        "popular": True,
    },
    {
        "id": "premium",
        "name": "Premium Box",
        "price": 149.99,
        "tagline": "For the ultimate Naija kitchen",
        "description": "20 premium items + proteins + seasonal surprises.",
        "items_count": 20,
        "serves": "4-6 people",
        "benefits": [
            "20 premium essentials + proteins",
            "Free express shipping",
            "Seasonal surprise item every month",
            "Priority AI chef assistant",
            "20% off all add-ons",
            "Pause or cancel anytime",
        ],
        "image": "https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80",
        "color": "dark",
    },
]
